# Generated by Django 3.0.4 on 2020-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_locality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
