# Generated by Django 3.0.4 on 2020-03-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
