# Generated by Django 3.0.4 on 2020-03-27 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200327_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
