# Generated by Django 3.0.4 on 2020-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200327_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
