# Generated by Django 3.0.4 on 2020-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_customuser_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_balance',
            field=models.FloatField(blank=True, default=1500, null=True),
        ),
    ]
